---
- hosts: webservers
  tasks:
    - debug:
        msg: 'This is debug message, it should execute only on linux'
      when: 
        - ansible_facts['os_family'] == "RedHat" 
        - ansible_facts['os_family'] == "RedHat"
