---
- hosts: all
  become: yes
  tasks:
    - name: Create group
      group:
        name: javahome
        state: present
    - name: Create users
      user:
        name: "{{item.name}}"
        group: "{{item.group}}"
      loop:
        - {name: 'hari', group: 'javahome'}
        - {name: 'Rakesh', group: 'javahome'}
